### ISSUE TITLE
咨询论文算法Online Vocabulary Updating Algorithm在代码中的位置及含义

### ISSUE THREAD

**Issue by ran-err** [cooelf/OpenIME#1]
你好，我是一名计算机研究生，阅读了Open Vocabulary Learning for Neural Chinese Pinyin IME论文之后，其中更新vocabulary的算法在手动模拟之后仍感觉没有理解到位。在 www.runoob.com 查看简单lua语法之后，我使用"vocabulary"/"ngram"/"break"/"6"分别进行了搜索并查看了大部分搜索位置，但是没有定位到源代码。于是有三个问题想要请教一下：

1. 我按照文章中的伪代码的理解，举了两个例子，我理解对了吗？
2. 文中Online Vocabulary Updating Algorithm算法在代码的什么位置？
3. 我尝试理解算法的过程有哪里是亟待提高的？

例1：

|      | 模型预测   | 用户选择   |
| ---- | ---------- | ---------- |
| 句子 | 我是中国人 | 我是种果人 |
| n=5  | 我是种果人 | 我是种果人 |

比较结果不符合注释`// both the first and last characters are different at least`所以执行第10行的break跳出循环，没有新词增加

例2：

|      | 模型预测                       | 用户选择                         |
| ---- | ------------------------------ | -------------------------------- |
| 句子 | 湖州看见美丽                   | 胡诌看见魅力                     |
| n=6  | 湖州看见美丽                   | **胡诌看见魅力**                 |
| n=5  | 湖州看见美、州看见美丽         | **胡诌看见魅**、**诌看见魅力**   |
| n=4  | 湖州看见、州看见美、看见美丽   | 胡诌看见、**诌看见魅**、看见魅力 |
| n=3  | 湖州看、州看见、看见美、见美丽 | 胡诌看、诌看见、看见魅、见魅力   |

表中粗体字被考虑加入vocabulary；n=3后由于没有mismatch而break出循环

**Comment by cooelf** [comment]
你好，抱歉才注意到这个提问。算法实现细节可以咨询我的co-author（huangyafang@sjtu.edu.cn），谢谢～
